version: '3'
services:
  app:
    build:
      context: .
    volumes:
    - ./:/var/www
    working_dir: /var/www

  web:
    image: nginx:alpine
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf

  database:
    image: mysql:5.6
    volumes:
    - dbdata:/var/lib/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
    - "33061:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=sykes_interview
    - MYSQL_USER=sykes
    - MYSQL_PASSWORD=sykesSecret

volumes:
  dbdata: ~
